---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      run: kibana
  replicas: 1
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
        - name: kibana-container
          image: kibana
          imagePullPolicy: Never
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 3600; done;"]
          ports:
            - containerPort: 5601
              hostPort: 5601
          env:
            - name: pod_namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
    #      resources:
    #          requests:
    #              memory: "2Gi"
    #              cpu: "1"
    #          limits:
    #              memory: "2Gi"
    #              cpu: "1"
    #  nodeSelector:
    #      kubernetes.io/hostname: 5geve-k3s-master-monit
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    run: kibana
spec:
  ports:
    - port: 5601
      protocol: TCP
  selector:
    run: kibana
