---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstashpipelinemanager
spec:
  selector:
    matchLabels:
      run: logstashpipelinemanager
  replicas: 1
  template:
    metadata:
      labels:
        run: logstashpipelinemanager
    spec:
      containers:
        - name: logstash-pipeline-manager-container
          image: logstash_pipeline_manager:v2
          imagePullPolicy: Never
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 3600; done;" ]
          ports:
            - containerPort: 5000
            - containerPort: 9600
            - containerPort: 8191
              hostPort: 8191
    #  nodeSelector:
    #      kubernetes.io/hostname: 5geve-k3s-master-monit
---
apiVersion: v1
kind: Service
metadata:
  name: logstashpipelinemanager
  labels:
    run: logstashpipelinemanager
spec:
  ports:
    - port: 8191
      protocol: TCP
  selector:
    run: logstashpipelinemanager

