global:

route:
  receiver: "default"
  group_wait: "1s"
  group_interval: "1s"
  repeat_interval: "1s"
  group_by:
  - "cluster"
  - "alertname"
  routes: []
receivers:
- name: 'default'
  webhook_configs:
  - send_resolved: true
    url: 'http://localhost:8080'
