apiVersion: v1
kind: Pod
metadata:
  name: elastalert
spec:
  containers:
    - name: elastalert-container
      image: elastalert:v2
      imagePullPolicy: Never
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "npm start", "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 3030
          hostPort: 3030
        - containerPort: 3333
          hostPort: 3333
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
