apiVersion: v1
kind: Pod
metadata:
  name: http-server
spec:
  containers:
    - name: http-server-container
      image: http_server
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "./entrypoint.sh; while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 8000
          hostPort: 8000
