apiVersion: v1
kind: Pod
metadata:
  name: log-pipeline-manager
spec:
  containers:
    - name: log-pipeline-manager-container
      image: log_pipeline_manager:v1
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 8987
          hostPort: 8987
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
