---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
spec:
  selector:
    matchLabels:
      run: elastalert
  replicas: 1
  template:
    metadata:
      labels:
        run: elastalert
    spec:
      containers:
        - name: elastalert-container
          image: elastalert:v2.6_DNS
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
            - containerPort: 3030
              # hostPort: 8191
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
---
apiVersion: v1
kind: Service
metadata:
  name: elastalert
  labels:
    run: elastalert
spec:
  ports:
    - port: 3030
      protocol: TCP
  selector:
    run: elastalert
