---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetchkafkatopic
spec:
  selector:
    matchLabels:
      run: fetchkafkatopic
  replicas: 1
  template:
    metadata:
      labels:
        run: fetchkafkatopic
    spec:
      containers:
        - name: fetch-kafka-topic-container
          image: fetch_kafka_topic
          imagePullPolicy: Never
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 3600; done;" ]
          ports:
            - containerPort: 8390
              hostPort: 8390
          command:
            - "/entrypoint.sh"
          args:
            - "kafka:9092"
    #  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
---
apiVersion: v1
kind: Service
metadata:
  name: fetchkafkatopic
  labels:
    run: fetchkafkatopic
spec:
  ports:
    - port: 8390
      protocol: TCP
  selector:
    run: fetchkafkatopic
