---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      run: kibana
  replicas: 1
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
        - name: kibana-container
          image: kibana:vDNS2
          imagePullPolicy: Never
          ports:
            - containerPort: 5601
              hostPort: 5601
          command:
            - "/entrypoint.sh"
          args:
            - "http://elasticsearch:9200"
    #      resources:
    #          requests:
    #              memory: "2Gi"
    #              cpu: "1"
    #          limits:
    #              memory: "2Gi"
    #              cpu: "1"
    #  nodeSelector:
    #      kubernetes.io/hostname: 5geve-k3s-master-monit
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    run: kibana
spec:
  ports:
    - port: 5601
      protocol: TCP
  selector:
    run: kibana
