---
global: null
route:
  receiver: "default"
  group_wait: "1s"
  group_interval: "1s"
  repeat_interval: "1s"
  group_by:
  - "cluster"
  - "alertname"
  routes: []
receivers:
- name: "default"
  webhook_configs:
  - send_resolved: true
    url: "http://localhost:8088"
- name: "5d77d2f1-712d-47ad-8210-7ec841f092a5"
  webhook_configs:
  - send_resolved: true
    url: "http://172.18.204.81:8080/sla_manager/notifications"
