

BOOTSTRAP_SERVERS = 'BOOTSTRAP_SERVERS'
FORWARD_TOPIC = 'FORWARD_TOPIC'
BACKWARD_TOPIC = 'BACKWARD_TOPIC'
LOGFILE = 'LOGFILE'
RVM_DAEMON_USER = 'RVM_DAEMON_USER'
RVM_DAEMON_WORKDIR = 'RVM_DAEMON_WORKDIR'
RVM_DAEMON_NAME = 'RVM_DAEMON_NAME'
AGENT_CONFIG = 'AGENT_CONFIG'

